# TODO: change name & description
name: flutter_template
description: Flutter Mobile App Template

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # json annotations
  json_annotation: ^4.3.0

  # icons
  material_design_icons_flutter: ^5.0.6295
  flutter_feather_icons: ^2.0.0+1
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.4
  unicons: ^2.0.2

  # screen util
  flutter_screenutil: ^5.0.0+2

  # intl
  intl: ^0.17.0

  # time ago
  timeago: ^3.1.0

  # enum to string
  enum_to_string: ^2.0.1

  # svg
  flutter_svg: ^0.23.0+1

  # package info
  package_info: ^2.0.2

  # firebase core
  firebase_core: ^1.10.0

  # firebase utils
  firebase_auth: ^3.2.0
  firebase_analytics: ^8.3.4
  firebase_dynamic_links: ^3.0.1
  firebase_remote_config: ^0.11.0+2
  firebase_messaging: ^11.1.0
  firebase_crashlytics: ^2.3.0
  firebase_app_check: ^0.0.3

  # badge utils
  flutter_app_badger: ^1.1.2

  # AdMob
  # admob_flutter: ^1.0.1
  # google_mobile_ads: ^0.13.6

  # share
  share: ^2.0.4

  # permission handler
  permission_handler: ^8.2.6

  # pickers
  image_picker: ^0.8.4+4
  image_cropper: ^1.3.1

  # blocs
  flutter_bloc: ^7.3.3
  equatable: ^2.0.3

  # carousel
  carousel_slider: ^4.0.0

  # spinkit
  flutter_spinkit: ^5.1.0

  # International Phone & Code Input
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.3.0

  # calendar
  # table_calendar: ^3.0.3

  # bottom sheet
  # modal_bottom_sheet: ^2.0.0

  # cached network image
  cached_network_image: ^3.1.0+1

  # rate my app
  rate_my_app: ^1.1.1

  # pull to refresh
  custom_refresh_indicator: ^1.0.0

  # page transition
  page_transition: ^2.0.4

  # dio - http client
  # dio: ^3.0.10

  # Date Time Picker
  flutter_datetime_picker: ^1.5.0

  # url launcher
  url_launcher: ^6.0.12

  # percent indicator
  percent_indicator: ^3.4.0

  # bottom sheet
  modal_bottom_sheet: ^1.0.0+1

  # faker
  faker: ^1.3.0

  # star rating
  smooth_star_rating: ^1.1.1

  # system settings
  system_settings: ^1.0.1

  # in app notification
  in_app_notification: ^1.0.1

  # device info
  device_info_plus: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.1

  dependency_validator: ^3.1.0

  build_runner: ^2.1.5
  json_serializable: ^6.0.1

  path_provider: ^2.0.6
  lint: ^1.1.1
  linter: ^1.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - i18n/

flutter_native_splash:
  color: "#FFFFFF"
  # TODO: change logo
  image: assets/flutter_template_logo.svg
  fullscreen: true
  android12: true
